// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Cliente
{
    public int ClienteID { get; set; }

    public string Nombre { get; set; }

    public string TipoCliente { get; set; }

    public string Direccion { get; set; }

    public string Telefono { get; set; }

    public string Correo { get; set; }

    public virtual ICollection<Venta> Venta { get; set; } = new List<Venta>();
}