// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class DetalleVenta
{
    public int DetalleID { get; set; }

    public int? VentaID { get; set; }

    public int? ProductoID { get; set; }

    public int Cantidad { get; set; }

    public decimal PrecioUnitario { get; set; }

    public virtual Producto Producto { get; set; }

    public virtual Venta Venta { get; set; }
}