// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class PuntoDeVenta
{
    public int PuntoID { get; set; }

    public string Nombre { get; set; }

    public string Direccion { get; set; }

    public int? ZonaID { get; set; }

    public virtual ICollection<Venta> Venta { get; set; } = new List<Venta>();

    public virtual ZonaGeografica Zona { get; set; }
}