// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class RutaEntrega
{
    public int RutaID { get; set; }

    public DateTime? Fecha { get; set; }

    public int? ZonaID { get; set; }

    public string Descripcion { get; set; }

    public string Estado { get; set; }

    public virtual ZonaGeografica Zona { get; set; }
}