// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class ZonaGeografica
{
    public int ZonaID { get; set; }

    public string Nombre { get; set; }

    public string Coordenadas { get; set; }

    public virtual ICollection<PuntoDeVenta> PuntoDeVenta { get; set; } = new List<PuntoDeVenta>();

    public virtual ICollection<RutaEntrega> RutaEntrega { get; set; } = new List<RutaEntrega>();
}